name: Banking Pipeline

on:
  schedule:
    - cron: '30 19 * * *'   # 1:00 AM IST (19:30 UTC)
  workflow_dispatch:         # Manual trigger

jobs:
  run-pipeline:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3

      - name: Run Banking Pipeline
        env:
          GCP_PROJECT: hello-dev-491512
        run: python main.py